// 返回版本号和更新提示
import CMD_BACK_VERSION from "./CMD_BACK_VERSION";
// 密码登录
import CMD_LOGIN_BY_PASSWORD from "./CMD_LOGIN_BY_PASSWORD";
//短信验证码获取
import CMD_SEND_SMS from "./CMD_SEND_SMS";
// 短信验证码登录
import CMD_LOGIN_BY_SMS from "./CMD_LOGIN_BY_SMS";
import CMD_LOGOUT from "./CMD_LOGOUT";
// 获取好友列表
import CMD_GET_FRIEND_LIST_INFO from "./CMD_GET_FRIEND_LIST_INFO";
// 心跳检测
import CMD_HEARTBEAT from "./CMD_HEARTBEAT";
// 大群列表
import CMD_GET_LARGE_GROUP_LIST from "./CMD_GET_LARGE_GROUP_LIST";

// 获取单聊消息
import CMD_GET_SINGLE_CHAT_MSG from "./CMD_GET_SINGLE_CHAT_MSG";
// 获取单聊消息
import CMD_GET_HAS_NEW_MSG_DIALOG_LIST from "./CMD_GET_HAS_NEW_MSG_DIALOG_LIST";
// 发送消息
import CMD_SEND_MSG from "./CMD_SEND_MSG";

// 握手
import CMD_HANDSHAKE from "./CMD_HANDSHAKE";
// 握手确认
import CMD_CONFIRM_HANDSHAKE from "./CMD_CONFIRM_HANDSHAKE";

// 获取大群的成员列表
import CMD_GET_LARGE_GROUP_MEM_LIST from "./CMD_GET_LARGE_GROUP_MEM_LIST";
// 移除大群成员
import CMD_REMOVE_LARGE_GROUP_MEM from "./CMD_REMOVE_LARGE_GROUP_MEM";
// 用户被挤掉或者踢出的情况
import CMD_KICK_USER from "./CMD_KICK_USER";
// 获取大群消息
import CMD_GET_LARGE_GROUP_MSG from "./CMD_GET_LARGE_GROUP_MSG";
// 有新消息推送
import CMD_PUSH_HAS_NEW_MSG_RSP from "./CMD_PUSH_HAS_NEW_MSG_RSP";
// 接受新消息推送
import CMD_PUSH_HAS_NEW_GREET_MSG from "./CMD_PUSH_HAS_NEW_GREET_MSG";
// 发送大群消息
import CMD_SEND_LARGE_GROUP_MSG from "./CMD_SEND_LARGE_GROUP_MSG";
//所有的单聊消息已达
import CMD_ALL_SINGLE_MSG_ARRIVAL from "./CMD_ALL_SINGLE_MSG_ARRIVAL";
//所有的大群消息已达
import CMD_ALL_LARGE_GROUP_MSG_ARRIVAL from "./CMD_ALL_LARGE_GROUP_MSG_ARRIVAL";
import CMD_GET_SIGNATURE from "./CMD_GET_SIGNATURE";
//获取单聊消息历史记录
import CMD_GET_SINGLE_CHAT_HISTORY_MSG from "./CMD_GET_SINGLE_CHAT_HISTORY_MSG";
//获取群聊消息历史记录
import CMD_GET_LARGE_GROUP_HISTORY_MSG from "./CMD_GET_LARGE_GROUP_HISTORY_MSG";
//大群详情
import CMD_GET_LARGE_GROUP_DETAIL from "./CMD_GET_LARGE_GROUP_DETAIL";
//通过uin或手机号查询是否是好友关系
import CMD_QUERY_FRIEND_RELATION_BY_UIN from "./CMD_QUERY_FRIEND_RELATION_BY_UIN";
// 回执
import CMD_MSG_ARRIVAL from './CMD_MSG_ARRIVAL';
// 大群消息已达回执
import CMD_LARGE_GROUP_MSG_ARRIVAL from './CMD_LARGE_GROUP_MSG_ARRIVAL';

// 获取大群管理员信息
import CMD_GET_LARGE_GROUP_CREATOR_ADMIN_INFO from './CMD_GET_LARGE_GROUP_CREATOR_ADMIN_INFO';


import CMD_NEW_PUSH_HAS_NEW_MSG from "./CMD_NEW_PUSH_HAS_NEW_MSG.js";

export default {
  ...CMD_BACK_VERSION,
  ...CMD_LOGIN_BY_PASSWORD,
  ...CMD_SEND_SMS,
  ...CMD_LOGIN_BY_SMS,
  ...CMD_LOGOUT,
  ...CMD_GET_FRIEND_LIST_INFO,
  ...CMD_HEARTBEAT,
  ...CMD_GET_LARGE_GROUP_LIST,
  ...CMD_GET_SINGLE_CHAT_MSG,
  ...CMD_GET_HAS_NEW_MSG_DIALOG_LIST,
  ...CMD_SEND_MSG,
  ...CMD_HANDSHAKE,
  ...CMD_CONFIRM_HANDSHAKE,
  ...CMD_GET_LARGE_GROUP_MEM_LIST,
  ...CMD_GET_LARGE_GROUP_MSG,
  ...CMD_PUSH_HAS_NEW_MSG_RSP,
  ...CMD_KICK_USER,
  ...CMD_GET_LARGE_GROUP_MSG,
  ...CMD_PUSH_HAS_NEW_GREET_MSG,
  ...CMD_SEND_LARGE_GROUP_MSG,
  ...CMD_ALL_SINGLE_MSG_ARRIVAL,
  ...CMD_ALL_LARGE_GROUP_MSG_ARRIVAL,
  ...CMD_GET_SIGNATURE,
  ...CMD_GET_SINGLE_CHAT_HISTORY_MSG,
  ...CMD_GET_LARGE_GROUP_HISTORY_MSG,
  ...CMD_GET_LARGE_GROUP_DETAIL,
  ...CMD_REMOVE_LARGE_GROUP_MEM,
  ...CMD_QUERY_FRIEND_RELATION_BY_UIN,
  ...CMD_MSG_ARRIVAL,
  ...CMD_LARGE_GROUP_MSG_ARRIVAL,
  ...CMD_NEW_PUSH_HAS_NEW_MSG,
  ...CMD_GET_LARGE_GROUP_CREATOR_ADMIN_INFO
};
